name: ServerCore
main: ServerCore\ServerCore
version: 1.2.2
api: 3.15.0
load: STARTUP
author: IceCruelStuff
description: An advanced core plugin
website: https://github.com/IceCruelStuff/ServerCore
depend: [PurePerms, EconomyAPI]
softdepend: [FactionsPro, ZMusicBox, KillChat]

permissions:
  command.warn:
    description: Allows player to use /warn
    default: op

  command.vanish:
    description: Allows player to use /vanish
    default: op

  command.forgive:
    description: Allows player to use /forgive
    default: op

  command.heal:
    description: Allows player to use /heal
    default: op

  command.ping:
    description: Allows player to use /ping
    default: true

  command.clear:
    description: Allows player to use /clear or /clearinv
    default: op

  command.hub:
    description: Allows player to use /hub or /lobby
    default: true

  command.fly:
    description: Allows player to use /fly
    default: op

  command.feed:
    description: Allows player to use /feed
    default: op

  command.info:
    description: Allows player to use /info
    default: true
