name: ServerCore
main: ServerCore\ServerCore
version: 1.2.1
api: 3.15.0
load: STARTUP
author: IceCruelStuff
description: An advanced core plugin
website: https://github.com/IceCruelStuff/ServerCore
depend: [PurePerms, EconomyAPI]
softdepend: [FactionsPro, ZMusicBox, KillChat]
commands:
  heal:
    description: Heal yourself
    permission: command.heal
    usage: "/heal"

  warn:
    description: Warns a player
    permission: command.warn
    usage: "/warn <user> <string:message>"

  vanish:
    description: Makes you invisible
    permission: command.vanish
    usage: "/vanish <player>"

  v:
    description: Makes you invisible
    permission: command.vanish
    usage: "/v <player>"

  forgive:
    description: Forgives a player
    permission: command.forgive
    usage: "/forgive <user>"

  ping:
    description: Returns player ping
    permission: command.ping
    usage: "/ping"

  clear:
    description: Clears player inventory
    permission: command.clear
    usage: "/clear"

  clearinv:
    description: Clears player inventory
    permission: command.clear
    usage: "/clearinv"

  fly:
    description: Allows player to fly
    permission: command.fly
    usage: "/fly"

  flight:
    description: Allows player to fly
    permission: command.fly
    usage: "/flight"

  hub:
    description: Teleports player to hub/lobby
    permission: command.hub
    usage: "/hub"
    
  lobby:
    description: Teleports player to hub/lobby
    permission: command.hub
    usage: "/lobby"

  feed:
    description: Feeds player
    permission: command.feed
    usage: "/feed"

  eat:
    description: Feeds player
    permission: command.feed
    usage: "/eat"

permissions:
  command.warn:
    description: Allows player to use /warn
    default: op

  command.vanish:
    description: Allows player to use /vanish
    default: op

  command.forgive:
    description: Allows player to use /forgive
    default: op

  command.heal:
    description: Allows player to use /heal
    default: op

  command.ping:
    description: Allows player to use /ping
    default: true

  command.clear:
    description: Allows player to use /clear or /clearinv
    default: op

  command.hub:
    description: Allows player to use /hub or /lobby
    default: true

  command.fly:
    description: Allows player to use /fly
    default: op

  command.feed:
    description: Allows player to use /feed
    default: op
