name: ServerCore
main: ServerCore\ServerCore
version: 1.2.1
api: 3.0.0, 4.0.0
load: STARTUP
author: IceCruelStuff
description: An advanced core plugin
website: https://github.com/IceCruelStuff/ServerCore
commands:
  heal:
    description: Heal yourself
    permission: command.heal
    usage: "/heal"

  warn:
    description: Warns a player
    permission: command.warn
    usage: "/warn <user> <string:message>"

  forgive:
    description: Forgives a player
    permission: command.forgive
    usage: "/forgive <user>"

  ping:
    description: Returns player ping
    permission: command.ping
    usage: "/ping"

  clear:
    description: Clears player inventory
    permission: command.clear
    usage: "/clear"

  clearinv:
    description: Clears player inventory
    permission: command.clear
    usage: "/clearinv"

  hub:
    description: Teleports player to hub/lobby
    permission: command.hub
    usage: "/hub"
    
  lobby:
    description: Teleports player to hub/lobby
    permission: command.hub
    usage: "/lobby"

permissions:
  command.warn:
    description: Allows player to use /warn
    default: op

  command.forgive:
    description: Allows player to use /forgive
    default: op

  command.heal:
    description: Allows player to use /heal
    default: op

  command.ping:
    description: Allows player to use /ping
    default: true

  command.clear:
    description: Allows player to use /clear or /clearinv
    default: op

  command.hub:
    description: Allows player to use /hub or /lobby
    default: true
