name: ServerCore
main: ServerCore\ServerCore
version: 2.1.1
api: 3.15.0
load: STARTUP
author: IceCruelStuff
description: An advanced core plugin for PocketMine-MP
website: https://github.com/IceCruelStuff/ServerCore
depend: [PurePerms, EconomyAPI]
softdepend: [FactionsPro, ZMusicBox, KillChat]
