name: ServerCore
main: ServerCore\ServerCore
version: 3.0.0-beta
api: 4.0.0
load: STARTUP
author: IceCruelStuff
description: An advanced core plugin for PocketMine-MP
website: https://github.com/IceCruelStuff/ServerCore
depend: [PurePerms, EconomyAPI]
softdepend: [FactionsPro, ZMusicBox, KillChat]
