---
# Commands:
info-ranks-command: "MVP: $5"
info-servers-command: "Welcome to our server!"

# Item names (for teleport/warp items):
Game-1-name: Game1
Game-2-name: Game2
Game-3-name: Game3

# Positions (for teleport/warp items):
Game-1-X: 0
Game-1-Y: 0
Game-1-Z: 0
Game-2-X: 0
Game-2-Y: 0
Game-2-Z: 0
Game-3-X: 0
Game-3-Y: 0
Game-3-Z: 0

# Rules (you can add more to the list)
rules:
  - No cheating or exploiting
  - No spamming
  - Respect all players

enable-ui: true
broadcast-player-joins: false
broadcast-admin-joins: false

# Includes an admin tag in join message
# This will only be activated if broadcast-admin-joins
# is turned on.
admin-tag: [ADMIN]
join-admin-tag: true
...
